### ISSUE TITLE
Dead link in the project description

### ISSUE THREAD

**Issue by jboockmann** [heiswayi/DirectoryCrawler#1]
The website given in the project description currently links to [https://heiswayi.github.io/2016/directory-crawler](https://heiswayi.github.io/2016/directory-crawler), which yields **404 – File not found**. You may want to update the link to [https://heiswayi.nrird.com/directory-crawler](https://heiswayi.nrird.com/directory-crawler).

**Comment by heiswayi** [comment]
Thanks for informing!
